version: "3.7"

services:
  www:
    build:
      context: www
      args:
        PHP_VERSION: ${PHP_VERSION}
        DRUSH_VERSION: ${DRUSH_VERSION}
    image: "${PROJECT_NAME}/www"
    container_name: "${PROJECT_NAME}_www"
    ports:
      - "${PORTS_WEB}:80"
    volumes:
      - ./www/php/config:/usr/local/etc/php/conf.d
      - ${PATH_APP}:/var/www/html

  database:
    image: mysql:${MYSQL_VERSION}
    container_name: "${PROJECT_NAME}_database"
    ports:
      - "${PORTS_MYSQL}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB_NAME
      MYSQL_USER: $MYSQL_DB_USER
      MYSQL_PASSWORD: $MYSQL_DB_PASSWORD
    volumes:
      - ./database/mysql/config:/etc/mysql/conf.d
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: